set_max_charging_current:
  name: set_max_charging_current
  description: Set maximal current per phase used for Charging
  fields:
    entity_id:
      name: Connector entity id
      description: Connector entity id
      required: true
    max_charging_current:
      name: Max charging current per phase
      description: Max charging current per phase
      required: true
      example: 20
